baseurl = "https://blog.setefaces.org"
languageCode = "en"
title = "Flesh eating bacteria."
theme = "hugo-dusk"
copyright = "Leandro Santiago - 2018"
pygmentsstyle = "native"
disqusShortname = "setefaces-blog"
googleAnalytics = ""
publishDir = "../public"

# Number of posts per page
Paginate = 5
enableRobotsTXT = true

[params.info]
adsense = "1426087445470523" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article

[params]
github = "leandrosansilva"
email = "leandro@setefaces.org"
linkedin = "leandrosansilva"

[params.matomoAnalytics]
siteID = 1

[taxonomies]
category = "categories"
tag = "tags"

[blackfriday]
hrefTargetBlank = true

[params.colors]
# hugo-dusk colors
background = "#101010" # background color for the site
main = "#99cc66"
text = "#dbdbdb"
code-quote-bg = "#1D1F21" # background color for quotes and code blocks
copyright = "#404040" # copyright text color

[[menu.main]]
name = "Posts"
weight = -120
identifier = "post"
url = "/post/"

[[menu.main]]
name = "Tags"
weight = -110
identifier = "tag"
url = "/tags/"
